version: "3.2"

services:
  artist4all_php:
    image: felixgalindo/php74apache
    container_name: 'artist4all_php'
    volumes:
      - ./artist4all_php/app:/var/www
    ports:
      - 81:80
    links: 
      - artist4all_db
    environment:
      - "TZ=Europe/Madrid"
      
  artist4all_angular:
    image: nginx:latest
    container_name: 'artist4all_angular'   
    ports: 
      - 80:80
    volumes: 
      - ./artist4all_angular/dist/Artist4All:/usr/share/nginx/html

  artist4all_db:
    image: mariadb:10.2
    container_name: 'artist4all_db'
    volumes:
      - ./artist4all_php/dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: artist4alldb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  artist4all_pma:
    image: phpmyadmin/phpmyadmin
    container_name: 'artist4all_pma'
    ports:
      - 8080:80
    links:
      - artist4all_db
    environment:
      PMA_HOST: artist4all_db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

